---
name: Workflow 1
"on": 
  push:
  pull_request:
      types: [opened, reopened]
jobs:
  workflow1_job1:
    runs-on: [self-hosted]
    steps:
      - name: 1st step
        run: echo "Hello from the 1st step"
      - name: 2nd step
        env:
          NON_SECRET: "I am not a secret"
          SECRET1: ${{ secrets.TESTING_SECRET }}
        run: |
          echo "Hello from the 2st step"
          echo "NON_SECRET: $NON_SECRET"
          echo "SECRET1: $SECRET1"
          if [ -z "$SECRET1" ]; then
            echo "SECRET1 is empty"
          else
            echo "SECRET1 is NOT empty"
          fi
  workflow1_job2:
    runs-on: [self-hosted]
    steps:
      - name: Successful step 1
        run: |
          echo "Hello from the step 1"
      - name: Failed step 2
        run: |
          echo "Hello from the step 2"
          exit 2
      - name: Successful step 3
        run: |
          echo "Hello from the step 3"
