---
name: Workflow 1
"on": 
  push:
  pull_request:
      types: [opened, reopened]
jobs:
  call-shared-action1:
      permissions:
        contents: read
        id-token: write
      uses: tomaso/shared-actions/.github/workflows/wf1.yaml@main

