---
name: Approve PR workflow
"on":
  pull_request:

jobs:
  input-test:
    inputs:
      myVar:
        description: 'myVar'
        required: true
    runs-on: ubuntu-latest
    steps:
      - name: Echo the var
        run: | 
          echo "Hello myVar is ${{ inputs.myVar }}"
